# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(333, 99)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setMinimumSize(QtCore.QSize(333, 99))
        Login.setMaximumSize(QtCore.QSize(333, 99))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-music-robot-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        self.auth_user_field = QtWidgets.QLineEdit(Login)
        self.auth_user_field.setGeometry(QtCore.QRect(40, 30, 113, 20))
        self.auth_user_field.setObjectName("auth_user_field")
        self.lineEdit = QtWidgets.QLineEdit(Login)
        self.lineEdit.setGeometry(QtCore.QRect(170, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(40, 10, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(170, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.login_button = QtWidgets.QPushButton(Login)
        self.login_button.setGeometry(QtCore.QRect(60, 60, 75, 23))
        self.login_button.setObjectName("login_button")
        self.close_button = QtWidgets.QPushButton(Login)
        self.close_button.setGeometry(QtCore.QRect(170, 60, 75, 23))
        self.close_button.setObjectName("close_button")

        self.retranslateUi(Login)
        self.login_button.clicked.connect(Login.login)
        self.close_button.clicked.connect(Login.quit)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.auth_user_field.setPlaceholderText(_translate("Login", "Username"))
        self.lineEdit.setPlaceholderText(_translate("Login", "License:"))
        self.label.setText(_translate("Login", "Username:"))
        self.label_2.setText(_translate("Login", "License:"))
        self.login_button.setText(_translate("Login", "Login"))
        self.close_button.setText(_translate("Login", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
